baseurl = "https://muwustudio.github.io/"
languageCode = "zh-cn"
theme = "stack"
paginate = 10
title = "牧屋 MUWU"

# 版权信息
copyright = "牧屋 MUWU"

# 文章目录配置
[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

# 代码高亮
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

# Markdown渲染
[markup.goldmark.renderer]
unsafe = true

# 相关文章推荐
[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

# 输出格式
[outputs]
home = ["HTML", "RSS", "JSON"]