baseURL = 'https://muwu-studio.github.io/'
languageCode = 'zh-cn'
title = '牧屋 MUWU - 游戏开发日志'
theme = 'PaperMod'

[params]
  description = "独立游戏开发者的技术博客"
  author = "牧屋 MUWU"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true